mmz-srf/srf-frontend-framework

source/_patterns/05-elements/content/media-caption.scss
source/_patterns/05-elements/content/spinner.twig
source/_patterns/10-components/audio/audio.scss
source/_patterns/10-components/audio/audio.twig
source/_patterns/10-components/audio/audio~loading.json
source/_patterns/10-components/video/video.scss
source/_patterns/_helpers.scss

srfcms-6684-player-loading-prototype

---

source/_patterns/10-components/comments/_comment.twig

dateline goes JS

---

source/_patterns/10-components/article-teaser/article-teaser.scss
source/_patterns/10-components/article-teaser/article-teaser.twig
source/_patterns/10-components/linkbox/linkbox.scss
source/_patterns/10-components/related-episodes/related-episodes.scss
source/_patterns/10-components/related-episodes/related-episodes.twig

https://srfmmz.atlassian.net/browse/SRFCMS-6745

SRFCMS-6745 Design Fixes 💉

---

source/_patterns/10-components/poll/poll.scss

Add styles for poll title

---

source/assets/js/srf-polis.js

srfcms-6781-polis-partial-info-text

---

source/_patterns/20-molecules/ratings/ratings.scss

srfcms-6679-pj-to-cms-show-results

---

source/_patterns/10-atoms/content/media-window.scss
source/_patterns/20-molecules/audio/audio.scss
source/_patterns/20-molecules/related-episodes/related-episodes.scss
source/_patterns/20-molecules/video-gallery/video-gallery.scss
source/_patterns/20-molecules/video/video.scss

srfcms-6291-related-videos-playing

---

source/_patterns/10-atoms/content/media-window.scss
source/_patterns/20-molecules/video/video.scss

srfcms-6994-make-fullscreen-great-again

---

source/_patterns/20-molecules/poll/poll.scss

SRFCMS-6940-texte

---

source/_patterns/10-atoms/content/media-window.scss
source/_patterns/20-molecules/video/video.scss

srfcms-6997-away-minute-line

---

source/_patterns/20-molecules/article-teaser/article-teaser.scss
source/_patterns/20-molecules/audio-gallery/audio-gallery.scss
source/_patterns/20-molecules/audio/audio.scss
source/_patterns/20-molecules/ch-map/ch-map.scss
source/_patterns/20-molecules/charts/charts.scss
source/_patterns/20-molecules/embed/embed.scss
source/_patterns/20-molecules/form/form.scss
source/_patterns/20-molecules/linkbox/linkbox.scss
source/_patterns/20-molecules/listmodule/listmodule.scss
source/_patterns/20-molecules/related-episodes/related-episodes.scss
source/_patterns/20-molecules/table-block/table-block.scss
source/_patterns/20-molecules/textbox/textbox.scss
source/_patterns/20-molecules/ticker/ticker.scss
source/_patterns/20-molecules/video-gallery/video-gallery.scss
source/_patterns/20-molecules/video-gallery/video-gallery.twig
source/_patterns/20-molecules/video/video.scss
source/_patterns/40-templates/article.scss
source/_patterns/_globals.scss
source/_patterns/_mixins.scss

article paddings margins size 1 (-8px removed)

srfcms-6649 article paddings margins size 1 (-8px removed)

---

source/_patterns/20-molecules/header/header.scss
source/_patterns/20-molecules/header/header.twig
source/_patterns/20-molecules/ratings/ratings.scss
source/assets/js/srf-header.js

srfcms-6060-hdr-the-2nd

---

source/_patterns/10-atoms/content/breadcrumb-link.scss
source/_patterns/20-molecules/image-carousel/image-carousel.scss
source/assets/js/srf-header.js

srfcms-7194-remove-header-navi-trap

---

source/_patterns/20-molecules/image-carousel/image-carousel.scss

srfcms-7204-img-gallery-arrow-fix

---

source/_patterns/10-atoms/content/tooltip.scss

give the thing some weight

---

source/_patterns/20-molecules/article-teaser/article-teaser.scss

- Removed full width on smartphone for article teaser (100vw breaks layout with scroll bar)

srfcms-7092-scroll-margins

---

source/_patterns/20-molecules/audio/audio.scss
source/_patterns/20-molecules/audio/audio.twig
source/_patterns/20-molecules/ch-map/ch-map.scss
source/_patterns/20-molecules/ch-map/ch-map.twig
source/assets/js/srf-chmap.js

srfcms-7221-cleanup-the-figure

---

source/_patterns/20-molecules/ticker/ticker.scss

Place ticker title on top of ticker info

---

source/_patterns/10-atoms/content/media-window.scss
source/assets/js/srf-carousels.js

srfcms-7203-re-reposition-gth-and-stuff

---

source/_patterns/20-molecules/audio-gallery/audio-gallery.scss

srfcms-7202-audio-gallery-resite-the-xth

---

source/_patterns/20-molecules/video-gallery/video-gallery.scss

srfcms-7219-video-gallery-cleanout-img-frames-a-gogo

---

source/_patterns/20-molecules/comments/_comment-reply.twig

srfcms-7270-form-attribute-on-label

---

source/_patterns/20-molecules/header/header.scss

srfcms-7275-no-scrolling-in-safari

---

source/_patterns/20-molecules/article-content/article-content.scss

SRFCMS-7096
This is a special use case for tinymce in editorial backend

Header Style for H1 in article-content

---

source/_patterns/10-atoms/content/media-window.scss
source/_patterns/20-molecules/audio/audio.scss
source/_patterns/20-molecules/audio/audio.twig
source/_patterns/20-molecules/listmodule/listmodule.scss
source/_patterns/20-molecules/video-gallery/video-gallery.scss

SRFCMS-7272 audio-/video integration for lists in RA

---

source/_patterns/10-atoms/content/media-window.scss

SRFCMS-7407 improving the opening and closing animations of the media window

---

source/assets/js/srf-comments.js

janrain-wizard-sumpf

---

package.json

Allow usage of a node version greater than 6

---

source/_patterns/10-atoms/navigation/expand-arrow.scss

Fixes the translateZ-Bug in Safari

---

source/_patterns/20-molecules/header/header.scss
source/_patterns/20-molecules/navigation/navigation.scss

Refinements for Footer and Stuff

---

source/_patterns/20-molecules/footer/footer.twig

SRFCMS-6242

---

source/_patterns/10-atoms/article/article-author.scss

margin between author and dateline is now 0px

SRFCMSAL-96 author dateline margin

---

source/_patterns/20-molecules/footer/footer.twig

Variable Fix

---

source/_patterns/00-introduction/intro.twig

documentation

---

source/_patterns/20-molecules/sharing-bar/sharing-bar.scss

SRFCMSAL-168 fitting sharingbar summary text on one line

---

source/assets/js/srf-comments.js

AL-192-success-screen-account-janrain

---

package.json

Making Babel Futureproof

---

source/_patterns/20-molecules/comments/comments.scss

no focus style on selected tab

---

bower.json

Removed empty bower.json

---

source/assets/js/srf-carousels.js

set accessibility to false to fix the jump (focus) problem

SRFCMSAL-251 Gallery Jump Problem

---

source/_patterns/10-atoms/links/block-link.scss
source/_patterns/20-molecules/article-teaser/article-teaser.scss
source/_patterns/20-molecules/linkbox/linkbox.scss
source/_patterns/20-molecules/related-episodes/related-episodes.scss

AL-37-related-articles

---

source/_patterns/20-molecules/ch-map/ch-map.scss

Fixes too small ch map problem in ie11

SRFCMSAL-312 Fixes too small ch map problem in ie11

---

composer.lock
source/_patterns/_globals.scss

set iframe border globally to 0 none

SRFCMSAL-8 set iframe border globally to 0 none

---

source/_patterns/20-molecules/video-gallery/video-gallery.scss

use static instead of unset since it's not supported by IE11 🙄

---

source/_patterns/20-molecules/audio/audio.scss
source/_patterns/20-molecules/ch-map/ch-map.scss
source/_patterns/20-molecules/charts/charts.scss
source/_patterns/20-molecules/media-caption/media-caption.scss
source/_patterns/20-molecules/swipe-module/swipe-module.twig
source/_patterns/20-molecules/video-gallery/video-gallery.scss

(and some minor problems that were discovered on the way)
noref

fixes the broken captions.

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss
source/_patterns/_breakpoints.scss

SRFCMSAL-377: use min-width to approximate flexbox behaviour on IE11

---

source/_patterns/10-atoms/text/article-author.scss
source/_patterns/10-atoms/text/article-author.twig

SRFCMSAL-250 Dateline

---

source/_patterns/20-molecules/media-window/media-window.scss
source/_patterns/40-templates/article.twig
source/_patterns/50-pages/article-basic.twig
source/_patterns/50-pages/article-complete.twig

Design-Review

---

source/_patterns/20-molecules/ticker/ticker.scss

SRFCMSDA-605-repositioning-ticker-new-msg-indicator

---

source/_patterns/20-molecules/media-window/media-window.scss

AL-466-mediawindow-close-button

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss
source/_patterns/20-molecules/textbox/textbox.twig

AL-413-autobox-design-fixes

---

source/assets/js/srf-charts.js

corrected async loading of AmCharts

---

source/_patterns/20-molecules/sharing-bar/sharing-bar.scss

fixes the amp css problem

---

source/_patterns/20-molecules/comments/comments.scss

AL-473-comment-field-max-width

---

source/_patterns/20-molecules/ticker/ticker.scss

srfcms-151-carto-for-ticker

---

package-lock.json
package.json

generate lock file, wildcarded everything possible

---

source/assets/js/srf-swipe-module.js

SRFCMSAL-385 Autobox Accessibility

---

source/_patterns/20-molecules/header/header.scss
source/_patterns/20-molecules/navigation/navigation.scss
source/assets/js/srf-header.js
source/assets/js/srf-navigation.js

POC: enable IOS scrolling in menu but not on page

---

source/_patterns/20-molecules/header/header.scss

change body bg color on mobile when menu is open for IOS overscroll

---

source/_patterns/20-molecules/blockquote/blockquote.scss

Changed blockquote text color

---

source/_patterns/10-atoms/navigation/breadcrumbs.twig

srfcms-da-816-breadcrumbs-for-google

---

source/_data/data.json
source/_patterns/20-molecules/blockquote/blockquote.scss

- Before pseudo element now on quote text itself (as after-element is)
- Removed negative margin from quote text
- Changed sample text to begin with a "W". This is a better sample since the beginning letter takes more space

srfcmsal-581-bugfix-missing-quote-margin

---

source/_patterns/20-molecules/table-block/table-block--nohead.twig
source/_patterns/20-molecules/table-block/table-block.twig

use tabindex to make table accessible by keyboard

SRFCMSAL-611 Keyboard access to table

---

source/assets/js/srf-shame.js

Adding carousel item to polyfill list

---

source/_patterns/_helpers.scss

New position of focusable offscreen text

SRFCMSAL-607 New position of focusable offscreen text

---

source/_patterns/20-molecules/media-caption/media-caption-with-image.twig
source/_patterns/20-molecules/media-caption/media-caption.scss

allow any image ratio in media caption

SRFCMSAL-606 allow any image ratio in media caption

---

source/_patterns/20-molecules/medium/medium.scss

SRFCMSAL-650 fixing medium hover bug

---

source/assets/js/srf-medium-hover.js

handle dynamic players

---

source/_patterns/10-atoms/indicators/carousel-counter.scss
source/_patterns/20-molecules/footer/footer.scss

Added a bit of font-smoothing

---

source/_patterns/20-molecules/textbox/textbox.scss

Minor Line-Height-Fix (🚔)

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss
source/_patterns/20-molecules/swipe-module/swipe-module.twig
source/_patterns/_globals.scss
source/_patterns/_shame.scss
source/assets/js/srf-swipe-module.js

Fokus Pokus

---

source/_patterns/10-atoms/navigation/breadcrumbs.scss

Consistent Padding

---

source/_patterns/20-molecules/table-block/table-block.scss

Smooth scrolling in tables

---

source/_patterns/10-atoms/navigation/breadcrumbs.scss

Better Breadcrumbs

---

source/_patterns/_globals.scss
source/assets/js/main.js
source/assets/js/srf-flying-focus.js

flying-focus js moved to fef

---

source/assets/js/srf-medium-hover.js

fix IE error

---

source/_patterns/10-atoms/navigation/breadcrumbs.scss
source/_patterns/10-atoms/text/article-lead.scss

font-size lead / breadcrumb margin

SRFCMSAL-742 RA Lead

---

source/_patterns/20-molecules/sharing-bar/sharing-bar.scss
source/_patterns/20-molecules/sharing-bar/sharing-bar.twig

hover color for sharing button

srfcmsal-703 link to comment

---

source/_patterns/20-molecules/media-window/media-window.scss

SRFCMSAL-672 increasing the touch area of the close button

---

source/_patterns/20-molecules/sharing-bar/sharing-bar.scss

🔬Sharing bar background is offwhite to match card

---

source/_patterns/20-molecules/charts/charts.scss
source/_patterns/20-molecules/charts/charts.twig
source/assets/demo/chart-data-column.json
source/assets/demo/chart-data-pie.json

srfcms-da-1200-flat-charts

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss

Remove swipe css to fix errors on safari with last element

---

source/_patterns/_helpers.scss

focusable link on top

---

source/assets/js/srf-swipe-module.js

Fix flying focus position after swipe

---

source/_patterns/40-templates/article.scss

article-min-height

---

source/_patterns/20-molecules/related-items-list/related-items-list.scss

use correct margin

---

source/_patterns/20-molecules/form/form.scss
source/_patterns/20-molecules/form/form.twig

Allow grouping of buttons

---

source/assets/js/srf-shame.js

append missing listing class

---

source/_patterns/10-atoms/navigation/breadcrumbs.scss
source/_patterns/40-templates/article.scss
source/_patterns/40-templates/article.twig

Added Flex to article

---

source/_patterns/20-molecules/header/header.twig
source/assets/js/srf-header.js

SRFCMSAL-935 - Mobile Burger Accessibility

---

source/_patterns/20-molecules/ticker/ticker.scss

srfcms-da-1510-ol-ala

---

source/_patterns/10-atoms/navigation/demo-search.twig
source/_patterns/10-atoms/navigation/search.scss

fix background color in legacy navigation search bar

---

source/_patterns/10-atoms/navigation/search.scss

use auto-prefixer because vendor-hack was not rendered

---

source/_patterns/20-molecules/table-block/table-block.scss

Added some styles for legacy tables

---

gulpfile.js
source/_meta/_00-head.twig
source/_patterns/50-pages/article-critical.json
source/_patterns/50-pages/article-critical.twig
source/assets/critical/_global.scss
source/assets/critical/_nav.scss
source/assets/critical/c_article.scss
source/assets/critical/c_landingpage.scss

Added critical CSS

---

source/_patterns/10-atoms/navigation/search.scss

should fix an issue on Edge where the result suggestions weren't shown

---

source/_patterns/10-atoms/form/select-menu.scss

NOREF-tmp-prefix-fix

---

source/_patterns/10-atoms/buttons/icon-button.scss
source/_patterns/30-organisms/masthead/_masthead-theme-settings.scss
source/_patterns/30-organisms/masthead/masthead.scss

Adds Interactivity-States to Menü-Itmes 🚀

---

source/_patterns/10-atoms/icons/svg-icon.twig

svg icon should be span and not div

---

source/_patterns/20-molecules/popup/popup.twig
source/assets/js/components/fef-popup.js
source/assets/js/main.js

FEF Popup Molecule

---

source/_patterns/20-molecules/medium/medium.scss
source/assets/critical/c_article.scss

player animation for mainMedia audio

---

source/assets/js/components/fef-modal.js

allow multiple focus targets in modals, but always take 1st

---

source/_patterns/10-atoms/navigation/onairnav-head.scss
source/_patterns/10-atoms/navigation/onairnav-link.scss
source/_patterns/20-molecules/onairnav/onairnav.scss

RLP-Header OnAir-Navigation Design-Fixes

---

source/_patterns/20-molecules/teaser/demo-teasers.twig
source/_patterns/20-molecules/teaser/teaser.scss
source/_patterns/20-molecules/teaser/teaser.twig
source/_patterns/20-molecules/teaser/teaser~l.json
source/_patterns/20-molecules/teaser/teaser~m.json
source/_patterns/20-molecules/teaser/teaser~s.json
source/_patterns/20-molecules/teaser/teaser~xl.json

Von S zu XL über M und L - wir haben sie alle.

Teaser-Formate

---

source/_patterns/30-organisms/modal/modal.scss
source/_patterns/_mixins.scss
source/assets/js/components/fef-modal.js

Momentum Scrolling as a mixin + implemented for modals

---

source/_patterns/20-molecules/medium/medium.scss

audiogallery fix

---

source/_patterns/10-atoms/buttons/load-more.scss
source/_patterns/10-atoms/buttons/load-more.twig
source/_patterns/10-atoms/icons/svg-icon.scss
source/_patterns/10-atoms/navigation/expand-icon.scss
source/_patterns/10-atoms/navigation/nav-item.scss
source/_patterns/10-atoms/navigation/nav-item.twig
source/_patterns/10-atoms/navigation/onairnav-head.scss
source/_patterns/10-atoms/navigation/onairnav-head.twig
source/_patterns/20-molecules/comments/_expand-switch.scss
source/_patterns/20-molecules/comments/comments.twig
source/_patterns/20-molecules/expandable-box/expandable-box.scss
source/_patterns/20-molecules/subnav/nav-group.scss
source/_patterns/20-molecules/subnav/subnav.twig
source/_patterns/20-molecules/swipe-module/swipe-module.scss
source/_patterns/_mixins.scss
source/assets/img/icon/caret_grey.svg
source/assets/img/icon/caret_red.svg
source/assets/img/icon/caret_white.svg
source/assets/img/icon/load_more.svg

Major refactoring of carets with new icons and snazzy mixin for carets

---

source/_patterns/_shame.scss

shame 🔔 - safari on iOS 10.* does not play nice.

---

source/_patterns/20-molecules/teaser/demo-teasers.twig
source/_patterns/20-molecules/teaser/teaser~l.json
source/_patterns/20-molecules/teaser/teaser~m.json
source/_patterns/20-molecules/teaser/teaser~s.json
source/_patterns/20-molecules/teaser/teaser~xl.json
source/_patterns/30-organisms/collection/collection.scss

fix demo page for teasers

---

source/_data/data.json
source/_patterns/20-molecules/teaser/teaser.twig
source/_patterns/30-organisms/collection/collection.twig
source/_patterns/50-pages/30-critical/_load-css-button.twig
source/_patterns/50-pages/30-critical/landingpage-critical.json
source/_patterns/50-pages/30-critical/landingpage-critical.twig
source/_patterns/_helpers.scss
source/assets/critical/_global.scss
source/assets/critical/c_article.scss
source/assets/critical/c_landingpage.scss

💅🏻 Dynamic RLP Preloader

---

source/_patterns/20-molecules/onairnav/onairnav.scss

use more flex to fix flex issues for old ios

---

source/_patterns/_layout.scss

Prevents click-through on dimmed background

---

source/_patterns/10-atoms/navigation/nav-item.scss

Fixes Padding on 3rd-Level-Navi-Items

---

source/_patterns/20-molecules/teaser/_teaser-theme-settings.scss
source/_patterns/20-molecules/teaser/teaser.scss

preemptive fix for faulty pull request ;)

---

source/_patterns/20-molecules/sticky-container/sticky-container.scss
source/_patterns/20-molecules/teaser/teaser.twig
source/_patterns/30-organisms/collection/collection.scss
source/_patterns/_variables.scss

fix gaps between collections + to edge, fix font

---

source/_patterns/10-atoms/navigation/nav-item.scss

i'm schubsing pixel everyday

---

source/_patterns/20-molecules/teaser/teaser.scss

let's give the users twice as long to admire ze animations, ja?

---

source/_patterns/_fonts.scss

remove importants to fix AMP

---

source/_patterns/30-organisms/collection/collection.scss

hover/active state color for collection links (with theme)

---

source/_patterns/20-molecules/teaser/teaser.scss

simple display of static teasers

---

source/_patterns/10-atoms/navigation/search.twig
source/assets/js/components/fef-search.js

SRFAL-1260 Search-Accessibility

---

source/_patterns/10-atoms/form/select-menu.scss
source/_patterns/_shame.scss

prettifying select for ie? hopefully!

---

source/_patterns/_shame.scss

SRFCMSAL-1258 fixing collection border problems in IE11

---

source/assets/js/components/fef-modal.js

SRFCMSAL-1338 - focusable modal close button (a11y improvement)

---

source/_patterns/_shame.scss

Adds anti-aliasing to Dark-Mobule-Close-Button

---

source/_patterns/10-atoms/navigation/breadcrumbs.twig

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1457

Breadcrumb A11Y

---

source/assets/js/srf-header.js

set focus after transition ended

---

source/_patterns/20-molecules/navigation/globalnav.twig
source/_patterns/20-molecules/navigation/navigation.twig
source/_patterns/30-organisms/rlp-footer/rlp-footer.twig

rename "Über SRF" to "Hallo SRF!"

---

source/assets/js/components/fef-search.js

use correct flying-focus js path

---

source/_patterns/20-molecules/navigation/globalnav.twig
source/_patterns/20-molecules/navigation/navigation.twig
source/_patterns/20-molecules/onairnav/onairnav.twig

changes texts in header/footer/menu

---

source/_patterns/30-organisms/collection/collection.scss

add color transition for title-links on unthemed collections

---

source/_patterns/20-molecules/onairnav/onairnav.twig
source/_patterns/20-molecules/teaser/teaser.scss
source/assets/js/components/fef-subnav.js

SRFCMSAL-1334 - Onair Livestream Fokus States

---

source/_patterns/10-atoms/navigation/nav-item.scss
source/_patterns/20-molecules/subnav/nav-group.scss
source/_patterns/20-molecules/subnav/nav-group.twig
source/_patterns/20-molecules/subnav/subnav.scss

https://srfmmz.atlassian.net/browse/SRFCMSAL-1294

🎨 Design-Changes and 🐛 Bug-Fixes for 3rd-Level Subnavigation

---

source/_patterns/10-atoms/navigation/breadcrumbs.twig

SRFCMSAL-1538
JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1538

Removes «Aktueller Artikel» from Tab-Index while keeping it available for Screen-Readers

---

source/_patterns/10-atoms/icons/svg-icon.scss
source/assets/img/icon/searchmenu.svg

SRFCMSAL-1466 new burger/search icon

---

source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-1450 RLP Frontend: Border bei Bildern auf Teaser

---

source/_patterns/10-atoms/links/block-link.scss

SRFCMSAL-1594
JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1594

SRFCMSAL-1594 Teaser Links Mindesthöhe (RLP Frontend)

---

source/_patterns/10-atoms/icons/svg-icon.scss
source/assets/img/close.svg
source/assets/img/icon/close-white.svg

srfcms-da-2271-new-img

---

source/_patterns/20-molecules/comments/comments.scss

srfcmsal 1416 - netiquette fix 

---

source/_patterns/30-organisms/collection/collection.scss

SRFCMSAL-1658 fixing size of first child in a swipeable collection

---

source/_patterns/10-atoms/links/block-link.scss
source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-1592: Fix teaser-links on hover/active

---

source/assets/critical/_header.scss

srfcms-da-2321-go-margin

---

source/_patterns/20-molecules/teaser/teaser.scss

NOREF: position longform teasers correctly

---

source/assets/js/components/fef-modal.js

🔥 Hotfix: use arrow functions for correct this context

---

source/assets/js/srf-shame.js

add meteo anchorman image to shame.js

---

source/_patterns/_variables.scss

SRFCMSAL-1610
https://srfmmz.atlassian.net/browse/SRFCMSAL-1610

💙 Adds new Meteo-Colors to Masthead

---

source/_patterns/30-organisms/collection/demo-collection.twig

SRFCMSAL-1618 fixing compact swipeable demo

---

source/_patterns/30-organisms/collection/collection.scss
source/_patterns/_variables.scss

💥 collection links color

---

source/_patterns/10-atoms/text/teaser-info.scss

SRFCMSAL-1706: fix spacing teaser info

---

source/_patterns/30-organisms/collection/demo-collection.twig

SRFCMSAL-1531: theme collection compact swipeable

---

source/assets/critical/_header.scss

SRFCMSAL-1616: branded header critical css

---

source/_patterns/20-molecules/teaser/_teaser-theme-settings.scss
source/_patterns/20-molecules/teaser/teaser--longform.twig
source/_patterns/20-molecules/teaser/teaser.scss
source/_patterns/30-organisms/collection/demo-collection.twig

Added teaserlinks to longform teasers

---

source/_patterns/20-molecules/teaser/_teaser-theme-settings.scss
source/_patterns/20-molecules/teaser/teaser.scss

Override default dark teaser background for longform

---

source/_patterns/30-organisms/masthead/masthead.scss

Make branded subnav a tad smaller

---

source/_patterns/20-molecules/teaser/teaser.scss
source/_patterns/_shame.scss

Reset height to play well with safari

---

source/_patterns/20-molecules/teaser/teaser.scss

Harmonize padding

---

source/_patterns/10-atoms/links/block-link.scss
source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-1806 fixing Links in XL-Teaser

---

source/_patterns/20-molecules/sharing-bar/sharing-bar.scss
source/assets/critical/c_article.scss

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1839

Fixes Sharing-Bar Margins

---

source/assets/critical/_header.scss

SRFCMSAL-1811 fixing font colors for ie11 in branded mastheads

---

source/_patterns/20-molecules/teaser/teaser.scss

Special treatment for xl-longform-images

---

source/_patterns/10-atoms/buttons/icon-button.scss
source/_patterns/10-atoms/icons/svg-icon.scss
source/_patterns/_shame.scss

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1575

 Fixes cut-off play-icon in masthead

---

source/_patterns/10-atoms/navigation/search.scss

NOREF-reindexx-search

---

source/assets/js/components/fef-expandable-box.js
source/assets/js/components/fef-modal.js

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1860

SRFCMSAL-1860: Chrome vs. prefers-reduced-motion

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss
source/_patterns/_mixins.scss

https://srfmmz.atlassian.net/browse/SRFCMSAL-1966

SRFCMSAL-1966: Autobox Arrow

---

source/_patterns/10-atoms/logos/main-logo.twig
source/_patterns/30-organisms/masthead/masthead.twig
source/_patterns/40-templates/landingpage.twig
source/assets/critical/_header.scss

SRFCMSAL-1929 improving accessibility of the masthead logo, link and <h1>

---

source/_patterns/10-atoms/form/radio-button.scss

Todo: Why !important?

---

source/assets/critical/c_landingpage.scss

removes shimmer from borderless/static collections

---

source/_patterns/20-molecules/footer/footer.twig
source/_patterns/30-organisms/rlp-footer/rlp-footer.twig

Add srgssr link

---

source/_patterns/20-molecules/media-caption/media-caption.scss
source/_patterns/20-molecules/media-window/media-window.scss
source/_patterns/20-molecules/medium/medium.scss
source/_patterns/20-molecules/medium/medium.twig
source/_patterns/30-organisms/video-gallery/video-gallery.scss

https://srfmmz.atlassian.net/browse/SRFCMSAL-1976

SRFCMSAL-1976: RLP-RA-Bugs

---

source/_patterns/_variables.scss

Update kultur and dok theme colors

---

source/_patterns/10-atoms/navigation/nav-item.scss
source/_patterns/20-molecules/subnav/nav-group.scss

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1915

SRFCMSAL-1915: Subnav/Dropdown – Back to the former design 🙄

---

source/_patterns/20-molecules/teaser/teaser.scss

JIRA: https://srfmmz.atlassian.net/browse/SRFCMSAL-1959

SRFCMSAL-1959 L-but-S-on-mobile Teaser-Lead Fix

---

source/_patterns/30-organisms/collection/_collection.twig
source/_patterns/30-organisms/collection/collection.scss

SRFCMSAL-1950: Adds new bottom-spacing for last collection on page

---

source/assets/js/components/fef-modal.js

SRFCMSAL-1934: A11Y - set everything else on the page to aria-hidden if modal is open

---

source/_patterns/10-atoms/icons/demo-svg-icon.twig
source/_patterns/10-atoms/icons/svg-icon.scss
source/_patterns/20-molecules/comments/_comment.twig
source/_patterns/20-molecules/comments/comments.scss
source/assets/img/icon/respond-blue-tiny.svg

SRFCMSAL-1549 Comments in Clarification FRONTEND

---

source/_patterns/main.scss
source/assets/critical/c_landingpage.scss

SRFCMSAL-1968 fix to avoid a FOUC after the preload state

---

source/_patterns/_shame.scss

SRFCMSAL-1989 Safari/VoiceOver now reads some of our semantical lists

---

source/assets/js/components/fef-subnav.js

SRFCMSAL-1918 fix for firefox' immediately closing 3rd level navigation bug

---

source/_patterns/10-atoms/navigation/_skiplink-target.twig
source/_patterns/20-molecules/navigation/globalnav.twig
source/_patterns/20-molecules/navigation/portalsnav--portallongnames.twig
source/_patterns/20-molecules/navigation/portalsnav.twig
source/_patterns/20-molecules/onairnav/onairnav.twig
source/_patterns/20-molecules/search-header/search-header.twig
source/_patterns/20-molecules/swipable-area/demo-swipeable-area.twig
source/_patterns/20-molecules/swipe-module/swipe-module.twig
source/_patterns/30-organisms/collection/_collection.twig
source/_patterns/30-organisms/masthead/masthead--compact.twig
source/_patterns/30-organisms/masthead/masthead--home.twig
source/_patterns/30-organisms/masthead/masthead--longportalnames.twig
source/_patterns/30-organisms/masthead/masthead.twig
source/_patterns/30-organisms/rlp-footer/rlp-footer.twig
source/_patterns/30-organisms/selectable/_selectable.twig
source/_patterns/40-templates/landingpage.twig

SRFCMSAL-1931 improving document structure for screenreaders

---

source/assets/js/components/fef-globalnav.js
source/assets/js/srf-navigation.js

set default state of global subnav menu to open

---

source/_patterns/50-pages/30-critical/compact-critical.json
source/_patterns/50-pages/30-critical/compact-critical.twig
source/assets/critical/c_landingpage.scss

copypasta from collection.scss and teaser.scss 🍝

SRFCMSAL-2042: loading state for compact collections are now compact

---

source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-2106 fixing the longform-teaser for safari

---

source/_patterns/20-molecules/swipable-area/swipeable-area.scss
source/_patterns/30-organisms/collection/collection.scss
source/_patterns/30-organisms/collection/collection~branded-dark.json
source/_patterns/_mixins.scss
source/_patterns/_variables.scss
source/assets/img/icon/caret_dark.svg

Add dark branded collection

---

source/_patterns/_globals.scss
source/_patterns/_variables.scss
source/assets/critical/_global.scss

SRFCMSAL-2152 fixing background-color of page and various content elements

---

source/_patterns/10-atoms/text/teaser-info.scss

correct margin for short-lead (L/XL) teasers

---

source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-2140 AND SRFCMSAL-1951

longform teaser imrpovements 

---

source/_patterns/10-atoms/feedback/spinner.scss

SRFCMSAL-2004 IE11 Spinner #FAIL

---

source/_patterns/10-atoms/text/article-title.scss

Make line height of article title relative

---

source/_patterns/20-molecules/swipe-module/swipe-module.md
source/assets/js/srf-swipe-module.js

srfcms-da-3029-play-search-design

---

source/_patterns/20-molecules/teaser/teaser.scss
source/_patterns/20-molecules/teaser/teaser.twig

this case is not possible anymore
SRFCMSAL-2189

Removes teaserlink-handling in xl-teaser if opinion is present

---

source/_patterns/20-molecules/medium/medium--audio-gallery.twig
source/_patterns/20-molecules/medium/medium--compact.twig
source/_patterns/20-molecules/medium/medium--fullwidth-element.twig
source/_patterns/20-molecules/medium/medium--related-items.twig
source/_patterns/20-molecules/medium/medium--vertical.twig
source/_patterns/20-molecules/medium/medium--video-gallery.twig
source/_patterns/20-molecules/medium/medium.scss
source/_patterns/20-molecules/medium/medium.twig

TME: medium notice

---

source/_patterns/20-molecules/sticky-container/sticky-container.scss

Fixes Gap between header and TME on Mobile

---

source/_patterns/_globals.scss

Touch Fix in App

---

source/assets/critical/_header.scss

Critical CSS Fix (Header)

---

source/_patterns/30-organisms/selectable/selectable.scss

disable user-select for selectable-wrapper

---

source/assets/critical/c_landingpage.scss

Prevent flickering fonts int page navi + title

---

source/assets/js/components/fef-search.js

srfcms-da-3222-header-light

---

source/_patterns/20-molecules/teaser/_teaser-theme-settings.scss
source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-2327: Longform-XL-Teasers' links appeared frazzled

---

source/_patterns/20-molecules/medium/medium.scss

allow pointer-events for image source link

---

source/assets/critical/c_article.scss

Fixes the loading state of the article:
OLD:
NEW:

SRFCMSAL-2252-fix-header-in-article

---

source/_patterns/10-atoms/navigation/nav-item.scss
source/_patterns/30-organisms/masthead/_masthead-theme-settings.scss
source/assets/img/icon/check-red.svg
source/assets/js/components/fef-subnav.js

SRFCMSAL-2227 and SRFCMSAL-2027

sub nav improvements

---

source/_patterns/20-molecules/swipable-area/swipeable-area.scss
source/_patterns/30-organisms/collection/collection.scss

rlp: swipeable collection caret

---

source/assets/js/components/fef-selectable.js
source/assets/js/components/fef-swipeable-area.js

rlp: fix swipeable collection empty state

---

source/_patterns/10-atoms/links/canton-link.twig
source/_patterns/20-molecules/canton-map/canton-map.scss
source/_patterns/_shame.scss

Prevent unused grid-area warning

---

source/_patterns/30-organisms/collection/collection.scss
source/assets/critical/c_landingpage.scss

swipeable collections correct paddings

---

source/assets/js/components/fef-flying-focus.js

SRFCMSAL-2121 Flying-Focus-Height-Problem-Fixer

---

source/_patterns/20-molecules/medium/medium.scss

SRFCMSAL-2333 Fix for Quad-Img in List-Module

---

source/_patterns/20-molecules/navigation/highlight-nav.scss

SRFCMSAL-2443 Fixes Color of highlight-nav__divider

---

source/_patterns/20-molecules/medium/medium.scss

NOREF Fixes TME

---

source/assets/js/classes/fef-storage.js

- Implemented here since we use it in three different places already

NOREF - Local storage self cleaning ID list

---

source/assets/js/components/fef-search.js

SRFCMSDA-3466-wrong-url

---

source/assets/critical/c_landingpage.scss

SRFCMSAL-2440 fixing the encore problem in stage build in critical css

---

source/_patterns/30-organisms/collection/collection.scss
source/_patterns/50-pages/40-demopages/rlp-elections-header.twig

SRFCMSAL-2423 cantonal header tweaks

---

source/assets/js/components/fef-search.js

srfcms-da-1617-analytics-module-weather

---

source/_patterns/20-molecules/medium/medium.scss

Show duration in TME

---

source/_patterns/20-molecules/media-caption/media-caption.scss
source/_patterns/20-molecules/medium/medium.scss

SRFCMSAL-2444 Fixes spacing between txt and img in audio-gallery

---

source/_patterns/30-organisms/collection/collection.scss

https://srfmmz.atlassian.net/browse/SRFCMSAL-2457

SRFCMSAL-2457 Swipables Spacing

---

source/assets/critical/c_landingpage.scss

SRFCMSAL-2457 Adds Collection-Fix to Critical-CSS

---

source/_patterns/20-molecules/medium/medium.scss

polls: correct player position 

---

source/_patterns/20-molecules/image-carousel/image-carousel.scss

image gallery arrows fix position

---

source/_patterns/20-molecules/scoreboard/scoreboard.scss

position mask on top

---

source/_patterns/10-atoms/logos/main-logo.twig
source/_patterns/10-atoms/navigation/search.twig
source/assets/js/components/fef-search.js

SRFCMSAL-2339 IE11 search problem

---

source/assets/js/components/fef-modal.js

SRFCMSAL-2516 - Safari/VO Focus problem

---

source/assets/js/components/fef-expandable-box.js
source/assets/js/components/fef-form-field.js
source/assets/js/components/fef-globalnav.js
source/assets/js/components/fef-modal.js
source/assets/js/components/fef-search.js
source/assets/js/components/fef-subnav.js
source/assets/js/srf-carousels.js
source/assets/js/srf-form-fields.js
source/assets/js/utils/fef-keycodes.js

Make keycodes global available

---

source/_patterns/30-organisms/collection/collection.scss
source/assets/critical/c_landingpage.scss

SRFCMSAL-2620 AND SRFCMSAL-2584

swipeable collections improvements

---

source/assets/js/components/fef-swipeable-area.js

Remove scroll tracking

---

source/_patterns/20-molecules/teaser/demo-teasers-live.twig
source/_patterns/20-molecules/teaser/demo-teasers-longform.twig
source/_patterns/30-organisms/collection/_collection.twig

Remove functionality for DUO: 2 L (2nd L looks like S on mobile)

---

source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-2664 fix for teaser__content/iframe height in safari/IE11

---

source/_patterns/10-atoms/buttons/button.scss

Fixed button hover color

---

source/assets/js/components/fef-search.js

SRFCMSAL-2589 type ahead fix

---

source/_patterns/10-atoms/indicators/score.scss
source/_patterns/20-molecules/scoreboard/scoreboard.scss
source/_patterns/20-molecules/teaser/teaser.scss

SRFCMSAL-2203 livecenter teaser design improvements

---

source/_patterns/20-molecules/navigation/globalnav.twig
source/_patterns/20-molecules/onairnav/onairnav.twig

PO Feedback (Renaming)

---

source/_patterns/20-molecules/article-teaser/article-teaser.twig

SRFCMSAL-2492 Related Article A11y

---

source/_patterns/20-molecules/image-carousel/image-carousel.scss
source/assets/js/srf-carousels.js

SRFCMSAL-2243-image-carousel-bugfixing

---

source/_patterns/30-organisms/modal/modal.scss

Fixed padding bottom of modal

---

source/_patterns/20-molecules/media-caption/media-caption-audio.twig
source/_patterns/20-molecules/media-caption/media-caption-video.twig

Srfcmsal 2491 Audio / Video Media Caption

---

source/_patterns/30-organisms/collection/demo-collection-swipeable.twig
source/assets/js/components/fef-swipeable-area.js

Swipeable Collections center correctly now 🙌

---

source/_patterns/main.global.scss
source/_patterns/main.page.scss

Move teaser label to global

---

source/assets/js/components/fef-modal.js

multiple modal open fix

---

source/_patterns/10-atoms/navigation/onairnav-link.scss
source/_patterns/20-molecules/onairnav/onairnav.twig

OnAirNav Design-Fixes

---

source/_patterns/10-atoms/buttons/button.scss
source/_patterns/10-atoms/buttons/button~call-to-action.json
source/_patterns/10-atoms/buttons/pill-button.scss
source/_patterns/50-pages/40-demopages/buttons.twig

Implement call to action buttons

---

source/_patterns/10-atoms/buttons/pill-button.scss

Srfcmsal-2831 webpush button fix

---

source/assets/js/srf-carousels.js

SRFCMSAL-2721 undo carousel chaos

---

source/assets/js/components/fef-search.js

prevent fef-search submit when input is empty

---

source/_patterns/40-templates/article.scss
source/_patterns/_shame.scss

SRFCMSAL-2806 Fixed background color of article in IE11

---

source/_patterns/10-atoms/buttons/pill-button.scss
source/_patterns/20-molecules/show-info/show-info.twig
source/_patterns/30-organisms/content-header/content-header.twig
source/_patterns/30-organisms/masthead/_masthead-theme-settings.scss
source/_patterns/30-organisms/masthead/demo-masthead-themes.twig
source/_patterns/50-pages/20-landingpage/landingpage-radio.json
source/_patterns/50-pages/30-critical/landingpage-critical-radio.json
source/_patterns/50-pages/40-demopages/buttons.twig
source/assets/critical/_header.scss

Harmonize class naming

---

source/_patterns/_variables.scss
source/assets/critical/c_landingpage.scss

Add serif-medium font

---

source/_patterns/20-molecules/special-teasers/teaser-cantons-nav.scss

SRFCMSAL-2889 fix cantons nav 

---

source/_patterns/20-molecules/swipe-module/swipe-module.scss

SRFCMSAL-2864 fixing arrows for IE in swipeable-modules

---

source/_patterns/_shame.scss
source/assets/js/srf-shame.js

SRFCMSAL-3029 Fix for flickering swipeable area in Safari/iOS 12

---

source/_patterns/30-organisms/collection/_collection.twig
source/_patterns/30-organisms/collection/collection.scss
source/_patterns/30-organisms/collection/demo-collection.twig

new: collection title link can be separate from the collection title

---

source/_patterns/10-atoms/navigation/search.scss

fix height search box

---

source/_patterns/10-atoms/navigation/search.scss

fix height search box 404 page

---

source/_patterns/20-molecules/comments/comments.scss

srf logo comments fix

---

source/_patterns/10-atoms/text/article-reference.scss
source/_patterns/10-atoms/text/article-reference.twig
source/_patterns/50-pages/10-article/article-complete.twig
source/_patterns/main.article.scss

Custom Atom for article-reference
